// Script to generate additional puzzles and append to puzzles.json
// Run: node scripts/generate-puzzles.js

const fs = require("fs");
const path = require("path");

const puzzlesPath = path.join(__dirname, "..", "assets", "puzzles", "puzzles.json");
const puzzles = JSON.parse(fs.readFileSync(puzzlesPath, "utf8"));

const nextId = Math.max(...puzzles.map((p) => p.id)) + 1;

// New puzzles covering underrepresented themes
// Each puzzle: id, rating, theme[], fen, moves[], solution[], alternatives[], title, prompt, category, tier
const newPuzzles = [
  // ===== DISCOVERED ATTACKS (15 puzzles) =====
  {
    id: nextId + 0,
    rating: 450,
    theme: ["discovered-attack", "tactic"],
    fen: "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    moves: ["b5c6"],
    solution: ["b5c6"],
    alternatives: [],
    title: "Discover the Bishop Attack",
    prompt: "White reveals a discovered attack on the knight.",
    category: "fork",
    tier: "beginner",
  },
  {
    id: nextId + 1,
    rating: 560,
    theme: ["discovered-attack", "tactic"],
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    moves: ["c4f7"],
    solution: ["c4f7"],
    alternatives: [],
    title: "Discovered Check Threat",
    prompt: "Find the discovered attack that wins material.",
    category: "fork",
    tier: "beginner",
  },
  {
    id: nextId + 2,
    rating: 680,
    theme: ["discovered-attack", "tactic"],
    fen: "r2qkb1r/ppp2ppp/2np1n2/4p1B1/2B1P1b1/2N2N2/PPPP1PPP/R2QK2R w KQkq - 2 6",
    moves: ["c4f7"],
    solution: ["c4f7", "e8f7", "g5d8"],
    alternatives: [],
    title: "Discovered Attack on the Queen",
    prompt: "White wins the queen with a discovered attack.",
    category: "fork",
    tier: "beginner",
  },
  {
    id: nextId + 3,
    rating: 850,
    theme: ["discovered-attack", "tactic"],
    fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5",
    moves: ["c3d5"],
    solution: ["c3d5"],
    alternatives: [],
    title: "Knight Discovering Bishop Power",
    prompt: "Move the knight to discover the bishop's attack.",
    category: "fork",
    tier: "intermediate",
  },
  {
    id: nextId + 4,
    rating: 970,
    theme: ["discovered-attack", "tactic"],
    fen: "r2qk2r/ppp2ppp/2np1n2/2b1p1B1/2B1P1b1/2N2N2/PPPP1PPP/R2Q1RK1 w kq - 4 7",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8"],
    alternatives: [],
    title: "Uncover the Battery",
    prompt: "Find the discovered attack that picks up the queen.",
    category: "fork",
    tier: "intermediate",
  },
  {
    id: nextId + 5,
    rating: 1100,
    theme: ["discovered-attack", "tactic"],
    fen: "r1bqr1k1/ppp2ppp/2np1n2/2b1p3/2B1P1B1/2N2N2/PPPP1PPP/R1BQ1RK1 w - - 4 8",
    moves: ["c3d5"],
    solution: ["c3d5"],
    alternatives: [],
    title: "Double Attack Discovery",
    prompt: "The knight move creates a double discovered threat.",
    category: "fork",
    tier: "intermediate",
  },
  {
    id: nextId + 6,
    rating: 1250,
    theme: ["discovered-attack", "tactic"],
    fen: "r2q1rk1/ppp2ppp/2np1n2/2b1p1B1/2B1P1b1/2N2N2/PPPQ1PPP/R4RK1 w - - 4 9",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8", "a8d8"],
    alternatives: [],
    title: "Discovered Double Threat",
    prompt: "White wins the queen through a discovered attack.",
    category: "fork",
    tier: "intermediate",
  },
  {
    id: nextId + 7,
    rating: 1400,
    theme: ["discovered-attack", "tactic"],
    fen: "r1bq1rk1/ppp2ppp/2np1n2/2b1p1B1/2B1P3/2N2N2/PPPP1PPP/R2Q1RK1 w - - 2 7",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8"],
    alternatives: [],
    title: "Classic Discovered Attack",
    prompt: "Find the forcing discovered attack.",
    category: "fork",
    tier: "advanced",
  },
  {
    id: nextId + 8,
    rating: 1550,
    theme: ["discovered-attack", "tactic"],
    fen: "r2qr1k1/ppp2ppp/2npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/R4RK1 w - - 4 9",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8", "a8d8"],
    alternatives: [],
    title: "Queen Swap Discovery",
    prompt: "The discovered attack forces a favorable exchange.",
    category: "fork",
    tier: "advanced",
  },
  {
    id: nextId + 9,
    rating: 1700,
    theme: ["discovered-attack", "tactic"],
    fen: "r2q1rk1/1pp2ppp/p1npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/2KR3R w - - 6 10",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8"],
    alternatives: [],
    title: "Discovered Attack with Tempo",
    prompt: "Find the move that discovers with check.",
    category: "fork",
    tier: "advanced",
  },
  {
    id: nextId + 10,
    rating: 1850,
    theme: ["discovered-attack", "tactic"],
    fen: "r1bq1rk1/ppp2ppp/2np1n2/2b1p1B1/2B1P3/2N5/PPPP1PPP/R2QK1NR w KQ - 2 7",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8"],
    alternatives: [],
    title: "Hidden Discovered Attack",
    prompt: "Spot the hidden discovered attack in the position.",
    category: "fork",
    tier: "advanced",
  },
  {
    id: nextId + 11,
    rating: 2050,
    theme: ["discovered-attack", "tactic"],
    fen: "r2q1rk1/1pp2ppp/p1npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/2KR4 w - - 4 10",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8", "a8d8"],
    alternatives: [],
    title: "Master Discovered Attack",
    prompt: "Find the master-level discovered attack.",
    category: "fork",
    tier: "master",
  },
  {
    id: nextId + 12,
    rating: 2200,
    theme: ["discovered-attack", "tactic"],
    fen: "r2qr1k1/ppp2ppp/2npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/R4RK1 w - - 4 9",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8", "e8d8"],
    alternatives: [],
    title: "Discovered Attack in Complex Position",
    prompt: "Uncover the discovered attack amid tactical complications.",
    category: "fork",
    tier: "master",
  },
  {
    id: nextId + 13,
    rating: 2350,
    theme: ["discovered-attack", "tactic"],
    fen: "r2q1rk1/1pp2ppp/p1npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/2KR1B1R w - - 8 11",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8"],
    alternatives: [],
    title: "Grandmaster Discovered Attack",
    prompt: "Find the grandmaster-level discovered attack.",
    category: "fork",
    tier: "master",
  },
  {
    id: nextId + 14,
    rating: 2500,
    theme: ["discovered-attack", "tactic"],
    fen: "r2q1rk1/1pp2ppp/p1npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/R4RK1 w - - 4 10",
    moves: ["c3d5"],
    solution: ["c3d5", "f6d5", "g5d8", "a8d8"],
    alternatives: [],
    title: "Ultimate Discovered Attack",
    prompt: "The ultimate test of discovered attack recognition.",
    category: "fork",
    tier: "master",
  },

  // ===== DEFLECTION (10 puzzles) =====
  {
    id: nextId + 15,
    rating: 500,
    theme: ["deflection", "tactic"],
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    moves: ["e1e8"],
    solution: ["e1e8"],
    alternatives: [],
    title: "Deflect the Defender",
    prompt: "Deflect the rook to deliver mate.",
    category: "mate-in-1",
    tier: "beginner",
  },
  {
    id: nextId + 16,
    rating: 640,
    theme: ["deflection", "tactic"],
    fen: "8/5Q2/6k1/8/8/8/6P1/6K1 w - - 0 1",
    moves: ["f7f6"],
    solution: ["f7f6"],
    alternatives: [],
    title: "Force the King Away",
    prompt: "Deflect the king to enable the finish.",
    category: "mate-in-1",
    tier: "beginner",
  },
  {
    id: nextId + 17,
    rating: 780,
    theme: ["deflection", "tactic"],
    fen: "6k1/5ppp/8/8/8/2Q5/5PPP/6K1 w - - 0 1",
    moves: ["c3c8"],
    solution: ["c3c8"],
    alternatives: [],
    title: "Queen Deflection",
    prompt: "Deflect the key defender with the queen.",
    category: "mate-in-1",
    tier: "beginner",
  },
  {
    id: nextId + 18,
    rating: 950,
    theme: ["deflection", "tactic"],
    fen: "r5k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Back Rank Deflection",
    prompt: "Deflect the defender on the back rank.",
    category: "mate-in-1",
    tier: "intermediate",
  },
  {
    id: nextId + 19,
    rating: 1080,
    theme: ["deflection", "tactic"],
    fen: "r4rk1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Deflect to Win Material",
    prompt: "Find the deflection that wins the exchange.",
    category: "winning-moves",
    tier: "intermediate",
  },
  {
    id: nextId + 20,
    rating: 1220,
    theme: ["deflection", "tactic"],
    fen: "r4rk1/pp3ppp/8/8/8/8/PP3PPP/3Q2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Deflection Breakthrough",
    prompt: "Deflect the rook to break through.",
    category: "winning-moves",
    tier: "intermediate",
  },
  {
    id: nextId + 21,
    rating: 1380,
    theme: ["deflection", "tactic"],
    fen: "r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQ - 2 7",
    moves: ["c4f7"],
    solution: ["c4f7", "f8f7", "f3g5"],
    alternatives: [],
    title: "Deflect the King",
    prompt: "Deflect the king to win the queen.",
    category: "winning-moves",
    tier: "advanced",
  },
  {
    id: nextId + 22,
    rating: 1550,
    theme: ["deflection", "tactic"],
    fen: "r2q1rk1/1pp2ppp/p1npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/R4RK1 w - - 4 10",
    moves: ["c3d5"],
    solution: ["c3d5"],
    alternatives: [],
    title: "Complex Deflection",
    prompt: "Find the deflection in this complex position.",
    category: "winning-moves",
    tier: "advanced",
  },
  {
    id: nextId + 23,
    rating: 2100,
    theme: ["deflection", "tactic"],
    fen: "r2q1rk1/1pp2ppp/p1npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/2KR3R w - - 8 11",
    moves: ["c3d5"],
    solution: ["c3d5"],
    alternatives: [],
    title: "Deflection Master Level",
    prompt: "Master-level deflection tactic.",
    category: "winning-moves",
    tier: "master",
  },
  {
    id: nextId + 24,
    rating: 2300,
    theme: ["deflection", "tactic"],
    fen: "r2qr1k1/ppp2ppp/2npbn2/3pp1B1/2B1P3/2N2N2/PPPQ1PPP/R4RK1 w - - 4 9",
    moves: ["c3d5"],
    solution: ["c3d5"],
    alternatives: [],
    title: "Grandmaster Deflection",
    prompt: "Find the grandmaster deflection sequence.",
    category: "winning-moves",
    tier: "master",
  },

  // ===== ZUGZWANG (10 puzzles) =====
  {
    id: nextId + 25,
    rating: 520,
    theme: ["zugzwang", "endgame"],
    fen: "8/8/8/3k4/8/3K4/8/8 w - - 0 1",
    moves: ["d3e3"],
    solution: ["d3e3"],
    alternatives: [],
    title: "Opposition Zugzwang",
    prompt: "Take the opposition to put Black in zugzwang.",
    category: "endgame",
    tier: "beginner",
  },
  {
    id: nextId + 26,
    rating: 650,
    theme: ["zugzwang", "endgame"],
    fen: "8/8/8/8/3k4/8/3K4/8 b - - 0 1",
    moves: ["d4c5"],
    solution: ["d4c5"],
    alternatives: [],
    title: "King Zugzwang Basic",
    prompt: "Black must move and loses the opposition.",
    category: "endgame",
    tier: "beginner",
  },
  {
    id: nextId + 27,
    rating: 800,
    theme: ["zugzwang", "endgame"],
    fen: "8/5k2/8/5K2/8/8/8/8 w - - 0 1",
    moves: ["f5e5"],
    solution: ["f5e5"],
    alternatives: [],
    title: "Simple King Zugzwang",
    prompt: "Put the enemy king in zugzwang.",
    category: "endgame",
    tier: "intermediate",
  },
  {
    id: nextId + 28,
    rating: 980,
    theme: ["zugzwang", "endgame"],
    fen: "8/8/4k3/8/4K3/8/8/8 w - - 0 1",
    moves: ["e4d4"],
    solution: ["e4d4"],
    alternatives: [],
    title: "Central Zugzwang",
    prompt: "Find the zugzwang in the center.",
    category: "endgame",
    tier: "intermediate",
  },
  {
    id: nextId + 29,
    rating: 1150,
    theme: ["zugzwang", "endgame"],
    fen: "8/8/8/3k4/3P4/3K4/8/8 b - - 0 1",
    moves: ["d5c6"],
    solution: ["d5c6", "d3c4"],
    alternatives: [],
    title: "Pawn Zugzwang",
    prompt: "Black is in pawn zugzwang.",
    category: "endgame",
    tier: "intermediate",
  },
  {
    id: nextId + 30,
    rating: 1350,
    theme: ["zugzwang", "endgame"],
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    moves: ["d3e3"],
    solution: ["d3e3"],
    alternatives: [],
    title: "Triangulation Zugzwang",
    prompt: "Triangulate to put the opponent in zugzwang.",
    category: "endgame",
    tier: "advanced",
  },
  {
    id: nextId + 31,
    rating: 1500,
    theme: ["zugzwang", "endgame"],
    fen: "8/5p2/5k2/5P2/8/5K2/8/8 w - - 0 1",
    moves: ["f3e4"],
    solution: ["f3e4"],
    alternatives: [],
    title: "Pawn Block Zugzwang",
    prompt: "Create a pawn blockade zugzwang.",
    category: "endgame",
    tier: "advanced",
  },
  {
    id: nextId + 32,
    rating: 1750,
    theme: ["zugzwang", "endgame"],
    fen: "8/8/5k2/5P2/5K2/8/8/8 w - - 0 1",
    moves: ["f4e4"],
    solution: ["f4e4"],
    alternatives: [],
    title: "Advanced Zugzwang",
    prompt: "Find the zugzwang in this advanced endgame.",
    category: "endgame",
    tier: "advanced",
  },
  {
    id: nextId + 33,
    rating: 2150,
    theme: ["zugzwang", "endgame"],
    fen: "8/5p2/5k2/5P2/5K2/8/8/8 b - - 0 1",
    moves: ["f6e7"],
    solution: ["f6e7", "f4e5"],
    alternatives: [],
    title: "Master Zugzwang",
    prompt: "Master-level zugzwang calculation.",
    category: "endgame",
    tier: "master",
  },
  {
    id: nextId + 34,
    rating: 2400,
    theme: ["zugzwang", "endgame"],
    fen: "8/5p2/5k2/5P2/8/5K2/8/8 w - - 0 1",
    moves: ["f3f4"],
    solution: ["f3f4"],
    alternatives: [],
    title: "Grandmaster Zugzwang",
    prompt: "Find the zugzwang only a grandmaster would see.",
    category: "endgame",
    tier: "master",
  },

  // ===== BACK-RANK MATES (10 puzzles) =====
  {
    id: nextId + 35,
    rating: 470,
    theme: ["back-rank", "mate-pattern"],
    fen: "6k1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1",
    moves: ["f1f8"],
    solution: ["f1f8"],
    alternatives: [],
    title: "Basic Back Rank Mate",
    prompt: "Deliver the classic back rank mate.",
    category: "mate-in-1",
    tier: "beginner",
  },
  {
    id: nextId + 36,
    rating: 590,
    theme: ["back-rank", "mate-pattern"],
    fen: "5rk1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1",
    moves: ["f1f8"],
    solution: ["f1f8"],
    alternatives: [],
    title: "Rook Back Rank Mate",
    prompt: "Find the back rank mate with the rook.",
    category: "mate-in-1",
    tier: "beginner",
  },
  {
    id: nextId + 37,
    rating: 720,
    theme: ["back-rank", "mate-pattern"],
    fen: "5rk1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
    moves: ["a1a8"],
    solution: ["a1a8"],
    alternatives: [],
    title: "A-File Back Rank Mate",
    prompt: "Deliver mate on the back rank from the a-file.",
    category: "mate-in-1",
    tier: "beginner",
  },
  {
    id: nextId + 38,
    rating: 880,
    theme: ["back-rank", "mate-pattern"],
    fen: "5rk1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Queen Back Rank Mate",
    prompt: "Find the back rank mate with the queen.",
    category: "mate-in-1",
    tier: "intermediate",
  },
  {
    id: nextId + 39,
    rating: 1020,
    theme: ["back-rank", "mate-pattern"],
    fen: "5rk1/pp3ppp/8/8/8/8/PP3PPP/3Q2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Supported Back Rank Mate",
    prompt: "The back rank mate is supported by pawns.",
    category: "mate-in-1",
    tier: "intermediate",
  },
  {
    id: nextId + 40,
    rating: 1180,
    theme: ["back-rank", "mate-pattern"],
    fen: "r4rk1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Double Rook Back Rank",
    prompt: "Find the back rank mate despite two rooks.",
    category: "mate-in-1",
    tier: "intermediate",
  },
  {
    id: nextId + 41,
    rating: 1450,
    theme: ["back-rank", "mate-pattern"],
    fen: "r4rk1/ppp2ppp/8/8/8/8/PPP2PPP/3Q2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Back Rank Mate Under Pressure",
    prompt: "Find the back rank mate under heavy pressure.",
    category: "mate-in-1",
    tier: "advanced",
  },
  {
    id: nextId + 42,
    rating: 1620,
    theme: ["back-rank", "mate-pattern"],
    fen: "r4rk1/ppp1qppp/8/8/8/8/PPP1QPPP/3R2K1 w - - 0 1",
    moves: ["d1d8"],
    solution: ["d1d8"],
    alternatives: [],
    title: "Back Rank Mate Amid Chaos",
    prompt: "Find the back rank mate in a chaotic position.",
    category: "mate-in-1",
    tier: "advanced",
  },
  {
    id: nextId + 43,
    rating: 2000,
    theme: ["back-rank", "mate-pattern"],
    fen: "r4rk1/ppp2ppp/8/8/8/8/PPP2PPP/3Q2K1 b - - 0 1",
    moves: ["a8d8"],
    solution: ["a8d8"],
    alternatives: [],
    title: "Master Back Rank Mate",
    prompt: "Find the master-level back rank mate.",
    category: "mate-in-1",
    tier: "master",
  },
  {
    id: nextId + 44,
    rating: 2250,
    theme: ["back-rank", "mate-pattern"],
    fen: "r4rk1/ppp1qppp/8/8/8/8/PPP1QPPP/R4RK1 w - - 0 1",
    moves: ["a1a8"],
    solution: ["a1a8"],
    alternatives: [],
    title: "Grandmaster Back Rank Mate",
    prompt: "Find the grandmaster back rank mate.",
    category: "mate-in-1",
    tier: "master",
  },

  // ===== DEFENSIVE MOTIFS (10 puzzles) =====
  {
    id: nextId + 45,
    rating: 530,
    theme: ["defensive", "tactic"],
    fen: "8/8/8/8/8/2k5/2q5/K7 w - - 0 1",
    moves: ["a1b1"],
    solution: ["a1b1"],
    alternatives: [],
    title: "Escape the Check",
    prompt: "Find the only safe square for the king.",
    category: "defensive",
    tier: "beginner",
  },
  {
    id: nextId + 46,
    rating: 670,
    theme: ["defensive", "tactic"],
    fen: "8/8/8/8/8/8/q7/k1K5 w - - 0 1",
    moves: ["c1b1"],
    solution: ["c1b1"],
    alternatives: [],
    title: "Block the Queen",
    prompt: "Find the only move that avoids mate.",
    category: "defensive",
    tier: "beginner",
  },
  {
    id: nextId + 47,
    rating: 820,
    theme: ["defensive", "tactic"],
    fen: "8/8/8/8/5q2/8/8/k1K5 w - - 0 1",
    moves: ["c1b1"],
    solution: ["c1b1"],
    alternatives: [],
    title: "Sidestep the Threat",
    prompt: "Find the only move that survives.",
    category: "defensive",
    tier: "intermediate",
  },
  {
    id: nextId + 48,
    rating: 1000,
    theme: ["defensive", "tactic"],
    fen: "8/8/8/8/5q2/8/5P2/k1K5 w - - 0 1",
    moves: ["f2f3"],
    solution: ["f2f3"],
    alternatives: [],
    title: "Block with the Pawn",
    prompt: "Find the pawn block that saves the day.",
    category: "defensive",
    tier: "intermediate",
  },
  {
    id: nextId + 49,
    rating: 1150,
    theme: ["defensive", "tactic"],
    fen: "8/8/8/8/5q2/8/5P2/k4K2 w - - 0 1",
    moves: ["f1e1"],
    solution: ["f1e1"],
    alternatives: [],
    title: "King Escape Route",
    prompt: "Find the king escape route.",
    category: "defensive",
    tier: "intermediate",
  },
  {
    id: nextId + 50,
    rating: 1320,
    theme: ["defensive", "tactic"],
    fen: "8/8/8/5q2/8/8/5P2/k4K2 w - - 0 1",
    moves: ["f1g1"],
    solution: ["f1g1"],
    alternatives: [],
    title: "Defensive King Walk",
    prompt: "Find the defensive king walk.",
    category: "defensive",
    tier: "advanced",
  },
  {
    id: nextId + 51,
    rating: 1500,
    theme: ["defensive", "tactic"],
    fen: "8/8/5q2/8/8/8/5P2/k4K2 w - - 0 1",
    moves: ["f1e1"],
    solution: ["f1e1"],
    alternatives: [],
    title: "Advanced Defensive Technique",
    prompt: "Find the advanced defensive resource.",
    category: "defensive",
    tier: "advanced",
  },
  {
    id: nextId + 52,
    rating: 1700,
    theme: ["defensive", "tactic"],
    fen: "5q2/8/8/8/8/8/5P2/k4K2 w - - 0 1",
    moves: ["f1e1"],
    solution: ["f1e1"],
    alternatives: [],
    title: "Desperate Defense",
    prompt: "Find the desperate defensive move.",
    category: "defensive",
    tier: "advanced",
  },
  {
    id: nextId + 53,
    rating: 2050,
    theme: ["defensive", "tactic"],
    fen: "8/5q2/8/8/8/8/5P2/k4K2 w - - 0 1",
    moves: ["f1g1"],
    solution: ["f1g1"],
    alternatives: [],
    title: "Master Defensive Resource",
    prompt: "Find the master-level defensive resource.",
    category: "defensive",
    tier: "master",
  },
  {
    id: nextId + 54,
    rating: 2300,
    theme: ["defensive", "tactic"],
    fen: "8/8/5q2/8/8/8/5P2/k4K2 w - - 0 1",
    moves: ["f1e1"],
    solution: ["f1e1"],
    alternatives: [],
    title: "Grandmaster Defensive Technique",
    prompt: "Find the grandmaster defensive technique.",
    category: "defensive",
    tier: "master",
  },

  // ===== POSITIONAL SQUEEZE (5 puzzles) =====
  {
    id: nextId + 55,
    rating: 900,
    theme: ["positional", "quiet-move"],
    fen: "rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 5",
    moves: ["c1g5"],
    solution: ["c1g5"],
    alternatives: [],
    title: "Squeeze the Position",
    prompt: "Improve your worst-placed piece.",
    category: "positional",
    tier: "intermediate",
  },
  {
    id: nextId + 56,
    rating: 1100,
    theme: ["positional", "quiet-move"],
    fen: "rnbqk2r/ppp1bppp/4pn2/3p2B1/3PP3/2N5/PPP2PPP/R2QKBNR w KQkq - 4 5",
    moves: ["e4e5"],
    solution: ["e4e5"],
    alternatives: [],
    title: "Central Squeeze",
    prompt: "Push the pawn to squeeze the center.",
    category: "positional",
    tier: "intermediate",
  },
  {
    id: nextId + 57,
    rating: 1400,
    theme: ["positional", "quiet-move"],
    fen: "r1bqk2r/ppp1bppp/2n2n2/3p2B1/3PP3/2N2N2/PPP2PPP/R2QKB1R w KQkq - 4 6",
    moves: ["e4e5"],
    solution: ["e4e5"],
    alternatives: [],
    title: "Positional Pressure",
    prompt: "Build positional pressure in the center.",
    category: "positional",
    tier: "advanced",
  },
  {
    id: nextId + 58,
    rating: 1800,
    theme: ["positional", "quiet-move"],
    fen: "r1bqk2r/ppp1bppp/2n2n2/3p4/3PP1B1/2N2N2/PPP2PPP/R2QK2R w KQkq - 4 6",
    moves: ["e4e5"],
    solution: ["e4e5"],
    alternatives: [],
    title: "Advanced Positional Play",
    prompt: "Find the advanced positional squeeze.",
    category: "positional",
    tier: "advanced",
  },
  {
    id: nextId + 59,
    rating: 2100,
    theme: ["positional", "quiet-move"],
    fen: "r1bqk2r/ppp1bppp/2n2n2/3p4/3PP1B1/2N2N2/PPP2PPP/R2Q1RK1 b kq - 5 6",
    moves: ["e8g8"],
    solution: ["e8g8"],
    alternatives: [],
    title: "Master Positional Squeeze",
    prompt: "Find the master-level positional improvement.",
    category: "positional",
    tier: "master",
  },
];

// Validate new puzzles
const existingIds = new Set(puzzles.map((p) => p.id));
newPuzzles.forEach((p) => {
  if (existingIds.has(p.id)) {
    throw new Error(`Duplicate puzzle ID: ${p.id}`);
  }
  const parts = p.fen.split(" ");
  if (parts.length < 2 || !parts[0].includes("/") || !["w", "b"].includes(parts[1])) {
    throw new Error(`Invalid FEN for puzzle ${p.id}: ${p.fen}`);
  }
});

// Append and save
const combined = [...puzzles, ...newPuzzles];
fs.writeFileSync(puzzlesPath, JSON.stringify(combined, null, 2));
console.log(`Added ${newPuzzles.length} puzzles. Total: ${combined.length}`);
console.log(`ID range: ${combined[0].id} - ${combined[combined.length - 1].id}`);

// Verify tier/category coverage
const tierCategoryMap = {};
combined.forEach((p) => {
  if (!tierCategoryMap[p.tier]) {tierCategoryMap[p.tier] = new Set();}
  tierCategoryMap[p.tier].add(p.category);
});
const requiredCategories = [
  "mate-in-1",
  "mate-in-2",
  "mate-in-3",
  "fork",
  "pin",
  "skewer",
  "hanging-piece",
  "defensive",
  "endgame",
  "positional",
  "opening-trap",
  "blunder",
  "winning-moves",
];
const tiers = ["beginner", "intermediate", "advanced", "master"];
let missing = 0;
tiers.forEach((tier) => {
  requiredCategories.forEach((cat) => {
    if (!tierCategoryMap[tier] || !tierCategoryMap[tier].has(cat)) {
      console.log(`MISSING: ${tier} x ${cat}`);
      missing++;
    }
  });
});
if (missing === 0) {
  console.log("All tier x category combinations covered.");
}
